/* eslint import/no-anonymous-default-export: [2, {"allowObject": true}] */
export default {
  languagesFrameworksTools: [
    "HTML",
    "CSS",
    "SCSS/LESS",
    "JavaScript",
    "TypeScript",
    "ReactJS",
    "NextJS",
    "Redux",
    "Angular",
    "NGRX",
    "Micro Front-Ends",
    "NodeJS",
    "Golang",
    "D3JS",
    "jQuery",
    "BackboneJS",
    "RequiredJS",
    "Vite",
    "WordPress",
    "Firebase",
    "Drupal",
  ],
  packageManagers: ["Webpack", "Babel", "Gulp", "Grunt", "Turbopack", "Mono Repo"],
  projectManagement: [
    "Jira",
    "Rally",
    "Git",
    "Bitbucket",
    "GitLab",
    "SVN",
    "TFS",
    "Postman",
    "Slack",
    "Trello",
  ],
  devOpsCloud: [
    "CI/CD",
    "Kubernetes",
    "Docker",
    "Nginx",
    "AWS",
    "Google Cloud",
    "Azure",
    "Vercel",
    "Netlify",
  ],
  education: {
    ug: {
      name: "Anna University, Chennai",
      type: "University",
      course: "B.Tech in Electronics Communication",
      duration: "2015",
    }
  },
  work: [
    {
      company: "Exium India Pvt Ltd",
      link: "https://exium.net/",
      role: "Lead Engineer",
      description: [
        "• Engaging in stories <b>estimation</b> in sprint/PI planning & work on challenging <b>user stories</b>.",
        "• Extensively created complex <b>UI screens & reusable</b> components using <b>ReactStrap & NextJS</b> best practices, used & integrated <b>Stripe</b> framework for <b>payment</b> functionalities.",
        "• Developed elegant <b>two-step authentication</b> flows for <b>login</b> using Microsoft Azure, Ping Identity, Okta, Email, SMS, and Google Authentications & can configurable via <b>SSO settings</b> form with captivating <b>UI designs.</b>",
        "• Handled complete app state using <b>Redux</b> & its methodologies & handled API layer using <b>Axios & Redux-Saga.</b>",
        "• Enabled secure signup with <b>Google's reCAPTCHA</b> for added security & implemented <b>UI session idle time check</b> and warning modal for <b>session</b> management.",
        "• Utilized Jest for comprehensive unit testing & generated coverage reports while each Jenkins build. Presented threat analysis, blocked URLs, policies, app usage, user data, and other portal functionalities with <b>beautiful graphs</b> using <b>Kibana framework.</b>",
        "• Leading team, Optimizing, refactoring, code deployments (staging/QA), code reviews, code complexity reduction will be daily routine.",
        "• Collaborating with BA’s, PO’s & stakeholders to understand <b>challenges, planning & proposing</b> better solutions to overcome blockers.",
      ],
      duration: "Jan 2022 - Present",
      achievements: [
        "• Successfully <b>migrated</b> an entire <b>React</b> application to <b>NextJS</b> in <b>short time</b> frame & <b>improved</b> application performance by <b>20%</b> through <b>NextJS server-side</b> approaches such as <b>SSG, SSR & others</b> wherever possible.",
      ],
    },
    {
      company: "Exium India Pvt Ltd",
      link: "https://service.exium.net/exium/sign-in",
      role: "Senior Software Engineer",
      description: [
        "• Developed a scalable <b>SPA Partner Portal</b> using <b>ReactStrap</b> (Material UI kind UI library) components, <b>NextJS & TypeScript</b> to build all UI pages in agile environment.",
        "• Handled <b>API failure</b> with three retries mechanisam, then will navigate to <b>network error</b> route &amp; on click of back button will navigate back to same page using <b>browser navigation</b> history API.",
        "• Created tables to show partners, users, companies &amp; handled <b>lazy loading</b> of the table for next set of lists to show <b>thousands of rows</b> once on click of next button.",
        "• <b>Integrated</b> different <b>ticketing engines</b> like ConnectWise, ServiceNow &amp; Autotask, based on this configuration added here will be validated it’s a valid config with ticketing platform &amp; will be raised <b>new tickets</b> when user tries to access <b>blocked/suspicious URLs.</b>",
        "• Handled <b>multiple sessions</b> in same browser window by allowing MSP can view his sub-MSP’s portals in <b>different tabs</b> &amp; by bypassing <b>login process</b> with just one click.",
        "• Same way MSP can view his <b>workspaces in same browser window</b> with multi sessions, by bypassing login with just one click.",
        "• Using <b>Stripe framework</b> created custom form, validations as per our needs &amp; handled <b>payment operations</b> using stripe framework for smooth, easy &amp; <b>secured payment experience.</b>",
        "• Using <b>stripe best practices</b> adding or updating card details with custom validations is done in a <b>secured manner</b> & can <b>download</b> payment details in <b>PDF format.</b>",
      ],
      duration: "Nov 2020 - Dec 2021",
      achievements: [
        "• Achieved a <b>50% reduction</b> in application build & deployment time by transitioning complete <b>Docker</b> steps from <b>npm to pnpm</b> and implementing other recommended <b>NextJS build optimization steps.</b>",
      ],
    },
    {
      company: "Accenture India",
      link: "",
      role: "Senior Analyst",
      description: [
        "• Built scalable <b>SPA</b> for both mobile and web applications using <b>PrimeNG UI</b> components in an <b>agile</b> environment, following wireframes provided by designers.",
        "• Employing <b>Angular 7</b> (upgraded to 10) and <b>TypeScript,</b> crafted this SPA with a focus on fast rendering and seamless authentication using <b>Microsoft Azure Authentication.</b>",
        "• Leveraged <b>Angular Interceptor</b> methodology to display <b>API failure</b> details in <b>barcode</b> format within <b>toastr</b> notifications.",
        "• Displayed <b>nearby</b> technician details within a few <b>miles’</b> radius on <b>Google Maps</b> inside the app, utilizing PrimeNG components and the <b>geolocation API.</b>",
        "• Used <b>Jasmine/Karma</b> to write <b>unit test</b> cases for components, services, pipes, directives & created <b>coverage</b> report on every <b>Jenkins build.</b>",
        "• Developed & mantained another sclalable using wed app using <b>JQuery Mobile & RequiredJS</b> for creating <b>SPA</b> kind of experience for faster rendering.",
        "• Used <b>MustacheJS</b> for creating reusable UI <b>logic-less templates</b> & also used <b>MomentJS</b> for time zone convertions.",
      ],
      duration: "Dec 2018 - Nov 2020",
      achievements: [
        "• Successfully completed a <b>Micro Front-end POC</b> in <b>Angular and React,</b> wherein I integrated <b>both apps</b> into a <b>single SPA</b>, akin to how the Amazon app incorporates Amazon Pay as a part of its shopping app.",
      ],
    },
    {
      company: "L&T Technology Services Pvt Ltd.",
      link: "",
      role: "Senior Software Engineer",
      description: [
        "• Used <b>Angular 5</b> for creating visual components like ECG wave forms, Alarms, pulse rate, RR, CO2 etc. of <b>patient vital</b> parameters & used <b>NGRX</b> for <b>State management</b> of the app.",
        "• Developed wave components, numeric components, Alarm component using <b>dynamic</b> components of <b>Kyma.io</b> platform (GE Healthcare internal only) for this <b>Tele-ICU</b> App.",
        "• Developed <b>Patient 12</b> leads <b>ECG</b> Wave & its <b>numeric</b> parameters by consuming Kyma.io platform visual & non-visual components.",
        "• Developed <b>Header Pane</b> for displaying patient details like name, patient time, DOB, Alarm volume control, Bed name & Care Area name.",
        "• With the help of <b>Web Socket</b> able to show <b>live patient</b> vital parameters with sample rate of 12 leads per <b>milli seconds</b>.",
        "• As a defects developer, I have gained valuable experience by playing <b>multiple roles</b>, including troubleshooting, fixing style and functionality issues, and addressing browser compatibility challenges.",
        "• Used <b>Jasmine/Karma</b> to write <b>unit test</b> cases for components, services, pipes, directives & created <b>coverage</b> report on every <b>Jenkins</b> build.",
      ],
      duration: "Oct 2016 - Dec 2018",
      achievements: [
        "• Accomplished <b>real-time live streaming</b> of patients' vital parameters to a <b>web page accessible globally</b>. Included live ECG and other graphs with customizable sweep speed.",
        "• These <b>live ECG graphs</b> efficiently handle a data rate of <b>12 samples per millisecond</b> through <b>web sockets.</b>",
      ],
    },
  ],
  accomplishments: [
  ],
};
